USE EXAM
go
CREATE TABLE EMPLOYEE(EmployeeID INT PRIMARY KEY,
	EmpName VARCHAR(20),
	Phone INT,
	Email VARCHAR(20))
CREATE TABLE COMPUTER(SerialNumber INT PRIMARY KEY,
	MfName VARCHAR(20),
	Model VARCHAR(10),
	Weight DECIMAL(2,2),
	EmployeeID INT,
	FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
	FOREIGN KEY (MfName) REFERENCES MANUFACTURER(MfName))
CREATE TABLE MANUFACTURER(Mfname VARCHAR(20) PRIMARY KEY,
	City VARCHAR(20),
	State VARCHAR(20))
INSERT INTO MANUFACTURER VALUES('HP','Pierre','South Dakota')
--Q1
SELECT MfName FROM MANUFACTURER WHERE State='South Dakota'
--Q2
SELECT AVG(Weight) AS 'Average Weight' FROM COMPUTER C INNER JOIN EMPLOYEE E ON C.EmployeeID=E.EmployeeID GROUP BY C.Weight
--Q3
ALTER TABLE EMPLOYEE ADD AreaCode INT
INSERT INTO EMPLOYEE VALUES(1,'Harry',1234,'harry@domain',2345)
SELECT EmpName FROM EMPLOYEE WHERE AreaCode LIKE '2%'
--Q4
SELECT SerialNumber FROM COMPUTER WHERE Weight<(SELECT AVG(Weight) FROM COMPUTER)
--Q5
SELECT MfName FROM COMPUTER WHERE MfName NOT IN(SELECT MfName FROM COMPUTER C INNER JOIN EMPLOYEE E ON C.EmployeeID=E.EmployeeID)
--Q6
SELECT E.EmpName,C.SerialNumber,M.City FROM EMPLOYEE E JOIN COMPUTER C ON E.EmployeeID=C.EmployeeID JOIN MANUFACTURER M ON C.MfName=M.Mfname 
--Q7
CREATE PROCEDURE GetComputerInfoFromEmployeeId
    @EmployeeId INT
AS
BEGIN
    SELECT COMPUTER.SerialNumber, MANUFACTURER.MfName, Model, weight
    FROM Computer
    JOIN EMPLOYEE ON COMPUTER.EmployeeId = EMPLOYEE.EmployeeId
    JOIN MANUFACTURER ON Computer.MfName = MANUFACTURER.MfName
    WHERE EMPLOYEE.EmployeeId = @EmployeeId;
END;
SELECT * FROM EMPLOYEE
EXEC GetComputerInfoFromEmployeeId @EmployeeId=1
